### ISSUE TITLE
Add .env to gitignore

### ISSUE THREAD

**Issue by rainqubit** [edhoguntur/books-rest_api#1]
## Issue
`.env` file is tracked by `git`, exposing all the sensitive info and could result in security breach, also not a good practice

## Suggested solution
1. add `.env` to `.gitigonre`
2. create new file similar to `.env` e.g `.env.def` but only contain the variables name instead
3. add instruction to `readme` to copy the `.env.def` file to `.env` and fill in the details

Example `.env.def` file
```
POSTGRES_USER=
POSTGRES_PASSWORD=
```

**Comment by edhoguntur** [comment]
Well Noted, thanks for sharing a good practical
